# Generated by Django 3.0.5 on 2020-04-05 21:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('item_description', models.TextField()),
                ('item_size', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('item_cost', models.IntegerField()),
            ],
        ),
    ]
